"""initial schema

Revision ID: ce909b3a0f14
Revises:
Create Date: 2026-07-17 14:14:49.998947
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "ce909b3a0f14"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Apply this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "pending_cleanup",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("target_type", sa.String(length=64), nullable=False),
        sa.Column("target_id", sa.String(length=128), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("purge_after", sa.DateTime(timezone=True), nullable=False),
        sa.Column("restored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("status", sa.String(length=64), nullable=False),
        sa.Column("confirmation_batch", sa.String(length=128), nullable=True),
        sa.CheckConstraint(
            "status IN ('pending', 'restored', 'awaiting_purge_confirmation')",
            name="ck_pending_cleanup_status",
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("target_type", "target_id", name="uq_pending_cleanup_target"),
    )
    with op.batch_alter_table("pending_cleanup", schema=None) as batch_op:
        batch_op.create_index(
            "ix_pending_cleanup_status_purge_after", ["status", "purge_after"], unique=False
        )

    op.create_table(
        "playlist",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_playlist_id", sa.String(length=128), nullable=False),
        sa.Column("name", sa.String(length=512), nullable=False),
        sa.Column("cover_url", sa.Text(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("refreshed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "provider", "provider_playlist_id", name="uq_playlist_provider_remote_id"
        ),
    )
    op.create_table(
        "setting_reference",
        sa.Column("key", sa.String(length=255), nullable=False),
        sa.Column("value_type", sa.String(length=32), nullable=False),
        sa.Column("value", sa.Text(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint(
            "value_type IN ('string', 'integer', 'boolean', 'credential_ref')",
            name="ck_setting_reference_value_type",
        ),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "song",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("provider", sa.String(length=32), nullable=False),
        sa.Column("provider_song_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=False),
        sa.Column("artist", sa.String(length=512), nullable=True),
        sa.Column("album", sa.String(length=512), nullable=True),
        sa.Column("duration_ms", sa.Integer(), nullable=True),
        sa.Column("cover_url", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("provider", "provider_song_id", name="uq_song_provider_remote_id"),
    )
    op.create_table(
        "audio_source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("source_type", sa.String(length=32), nullable=False),
        sa.Column("local_path", sa.Text(), nullable=False),
        sa.Column("display_name", sa.String(length=512), nullable=True),
        sa.Column("content_fingerprint", sa.String(length=128), nullable=True),
        sa.Column("availability", sa.String(length=32), nullable=False),
        sa.Column("checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.CheckConstraint(
            "source_type IN ('local_mp3', 'local_lrc')", name="ck_audio_source_local_only"
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("song_id", "source_type", name="uq_audio_source_song_type"),
    )
    op.create_table(
        "background_task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("task_type", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("progress", sa.Integer(), nullable=False),
        sa.Column("trace_id", sa.String(length=128), nullable=False),
        sa.Column("error_category", sa.String(length=64), nullable=True),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("related_song_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["related_song_id"],
            ["song.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("trace_id", name="uq_background_task_trace_id"),
    )
    with op.batch_alter_table("background_task", schema=None) as batch_op:
        batch_op.create_index(
            "ix_background_task_status_created_at", ["status", "created_at"], unique=False
        )

    op.create_table(
        "favorite",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("phrase", sa.Text(), nullable=False),
        sa.Column("normalized_phrase", sa.Text(), nullable=False),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("normalized_explanation", sa.Text(), nullable=False),
        sa.Column("source_line", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("favorite", schema=None) as batch_op:
        batch_op.create_index("ix_favorite_created_at", ["created_at"], unique=False)
        batch_op.create_index(
            "ix_favorite_normalized_explanation", ["normalized_explanation"], unique=False
        )
        batch_op.create_index("ix_favorite_normalized_phrase", ["normalized_phrase"], unique=False)
        batch_op.create_index(
            "ix_favorite_song_created_at", ["song_id", "created_at"], unique=False
        )

    op.create_table(
        "lyrics_document",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("capability", sa.String(length=16), nullable=False),
        sa.Column("offset_ms", sa.Integer(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("capability IN ('plain', 'line', 'word')", name="ck_lyrics_capability"),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "version", name="uq_lyrics_document_id_version"),
        sa.UniqueConstraint("song_id", "version", name="uq_lyrics_document_song_version"),
    )
    with op.batch_alter_table("lyrics_document", schema=None) as batch_op:
        batch_op.create_index(
            "uq_lyrics_document_current_song",
            ["song_id"],
            unique=True,
            sqlite_where=sa.text("is_current = 1"),
        )

    op.create_table(
        "playback_preference",
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("lyrics_offset_ms", sa.Integer(), nullable=False),
        sa.Column("source_preference", sa.String(length=16), nullable=False),
        sa.CheckConstraint(
            "source_preference IN ('online', 'local')", name="ck_playback_source_preference"
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
        ),
        sa.PrimaryKeyConstraint("song_id"),
    )
    op.create_table(
        "playlist_song",
        sa.Column("playlist_id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("availability", sa.String(length=32), nullable=False),
        sa.ForeignKeyConstraint(
            ["playlist_id"],
            ["playlist.id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
        ),
        sa.PrimaryKeyConstraint("playlist_id", "song_id"),
        sa.UniqueConstraint("playlist_id", "position", name="uq_playlist_song_position"),
    )
    with op.batch_alter_table("playlist_song", schema=None) as batch_op:
        batch_op.create_index(
            "ix_playlist_song_playlist_position", ["playlist_id", "position"], unique=False
        )

    op.create_table(
        "analysis_version",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("lyrics_document_id", sa.Integer(), nullable=False),
        sa.Column("lyrics_version", sa.Integer(), nullable=False),
        sa.Column("lyrics_content_hash", sa.String(length=64), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("prompt_version", sa.String(length=64), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("status = 'complete'", name="ck_analysis_complete_only"),
        sa.ForeignKeyConstraint(
            ["lyrics_document_id", "lyrics_version"],
            ["lyrics_document.id", "lyrics_document.version"],
            name="fk_analysis_lyrics_version",
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("analysis_version", schema=None) as batch_op:
        batch_op.create_index(
            "ix_analysis_version_lyrics_version",
            ["lyrics_document_id", "lyrics_version"],
            unique=False,
        )
        batch_op.create_index(
            "uq_analysis_version_current_song",
            ["song_id"],
            unique=True,
            sqlite_where=sa.text("is_current = 1"),
        )

    op.create_table(
        "lyrics_line",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lyrics_document_id", sa.Integer(), nullable=False),
        sa.Column("stable_line_id", sa.String(length=128), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=True),
        sa.Column("end_ms", sa.Integer(), nullable=True),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint(
            "end_ms IS NULL OR (start_ms IS NOT NULL AND end_ms >= start_ms)",
            name="ck_lyrics_line_time_order",
        ),
        sa.ForeignKeyConstraint(
            ["lyrics_document_id"],
            ["lyrics_document.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lyrics_document_id", "position", name="uq_lyrics_line_position"),
        sa.UniqueConstraint(
            "lyrics_document_id", "stable_line_id", name="uq_lyrics_line_stable_id"
        ),
    )
    op.create_table(
        "qa_message",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("song_id", sa.Integer(), nullable=False),
        sa.Column("conversation_id", sa.String(length=128), nullable=False),
        sa.Column("lyrics_document_id", sa.Integer(), nullable=True),
        sa.Column("lyrics_content_hash", sa.String(length=64), nullable=True),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("related_line_id", sa.String(length=128), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("role IN ('user', 'assistant')", name="ck_qa_message_role"),
        sa.CheckConstraint(
            "(lyrics_document_id IS NULL AND lyrics_content_hash IS NULL) OR "
            "(lyrics_document_id IS NOT NULL AND lyrics_content_hash IS NOT NULL)",
            name="ck_qa_lyrics_binding",
        ),
        sa.ForeignKeyConstraint(
            ["lyrics_document_id"],
            ["lyrics_document.id"],
        ),
        sa.ForeignKeyConstraint(
            ["song_id"],
            ["song.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("qa_message", schema=None) as batch_op:
        batch_op.create_index(
            "ix_qa_message_conversation_created_at", ["conversation_id", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_qa_message_song_created_at", ["song_id", "created_at"], unique=False
        )

    op.create_table(
        "line_analysis",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("analysis_version_id", sa.Integer(), nullable=False),
        sa.Column("lyrics_line_id", sa.Integer(), nullable=False),
        sa.Column("translation", sa.Text(), nullable=False),
        sa.Column("surface_meaning", sa.Text(), nullable=False),
        sa.Column("contextual_meaning", sa.Text(), nullable=False),
        sa.Column("slang_notes", sa.Text(), nullable=False),
        sa.Column("user_modified", sa.Boolean(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["analysis_version_id"],
            ["analysis_version.id"],
        ),
        sa.ForeignKeyConstraint(
            ["lyrics_line_id"],
            ["lyrics_line.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("analysis_version_id", "lyrics_line_id", name="uq_line_analysis_line"),
    )
    op.create_table(
        "word_timing",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("lyrics_line_id", sa.Integer(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.Column("start_ms", sa.Integer(), nullable=False),
        sa.Column("end_ms", sa.Integer(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.CheckConstraint("end_ms >= start_ms", name="ck_word_timing_time_order"),
        sa.ForeignKeyConstraint(
            ["lyrics_line_id"],
            ["lyrics_line.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("lyrics_line_id", "position", name="uq_word_timing_position"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this revision."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("word_timing")
    op.drop_table("line_analysis")
    with op.batch_alter_table("qa_message", schema=None) as batch_op:
        batch_op.drop_index("ix_qa_message_song_created_at")
        batch_op.drop_index("ix_qa_message_conversation_created_at")

    op.drop_table("qa_message")
    op.drop_table("lyrics_line")
    with op.batch_alter_table("analysis_version", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_analysis_version_current_song", sqlite_where=sa.text("is_current = 1")
        )
        batch_op.drop_index("ix_analysis_version_lyrics_version")

    op.drop_table("analysis_version")
    with op.batch_alter_table("playlist_song", schema=None) as batch_op:
        batch_op.drop_index("ix_playlist_song_playlist_position")

    op.drop_table("playlist_song")
    op.drop_table("playback_preference")
    with op.batch_alter_table("lyrics_document", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_lyrics_document_current_song", sqlite_where=sa.text("is_current = 1")
        )

    op.drop_table("lyrics_document")
    with op.batch_alter_table("favorite", schema=None) as batch_op:
        batch_op.drop_index("ix_favorite_song_created_at")
        batch_op.drop_index("ix_favorite_normalized_phrase")
        batch_op.drop_index("ix_favorite_normalized_explanation")
        batch_op.drop_index("ix_favorite_created_at")

    op.drop_table("favorite")
    with op.batch_alter_table("background_task", schema=None) as batch_op:
        batch_op.drop_index("ix_background_task_status_created_at")

    op.drop_table("background_task")
    op.drop_table("audio_source")
    op.drop_table("song")
    op.drop_table("setting_reference")
    op.drop_table("playlist")
    with op.batch_alter_table("pending_cleanup", schema=None) as batch_op:
        batch_op.drop_index("ix_pending_cleanup_status_purge_after")

    op.drop_table("pending_cleanup")
    # ### end Alembic commands ###
